services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    environment:
      - NODE_ENV=development
      - USER_NAME=${USER_NAME}   # Use your username here
    command: pnpm start

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - NODE_ENV=development
      - USER_NAME=${USER_NAME}   # Use your username here
    command: pnpm run dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    environment:
      - USER_NAME=${USER_NAME}  # This is important for subdomain
