services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    environment:
      - NODE_ENV=development
      - USER_NAME=${VITE_USER_NAME}
    command: pnpm start

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - NODE_ENV=development
      - USER_NAME=${VITE_USER_NAME}
      - VITE_USER_NAME=${VITE_USER_NAME}
    command: pnpm run dev
