services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    environment:
      - NODE_ENV=development
      - USER_NAME=bonifasius
    command: pnpm start

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - NODE_ENV=development
      - USER_NAME=bonifasius
      - VITE_USER_NAME=bonifasius
    command: pnpm run dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount your nginx.conf to Nginx
    depends_on:
      - frontend
      - backend
